### PR TITLE
Upgrade PHPCS

### PR DESCRIPTION
**Pull request by MidnightDesign**
* Require `"slevomat/coding-standard": "^6.0 || ^7.0"`
* Run PHPCS in GitHub Actions
* Add some missing type annotations

### CODE REVIEW

**Comment by MidnightDesign** [comment]
Are Workflows disabled?

**Comment by marcospassos** [comment]
Hi @MidnightDesign, thank you for your contribution!

No, it isn't. Maybe because there is no workflow on master or because the PR is still on draft.

**Comment by MidnightDesign** [comment]
@marcospassos I've marked it as ready to review and they still won't run.

**Comment by MidnightDesign** [comment]
@marcospassos Any idea? Maybe the first workflow run must be triggered by the repository owner or something?

**Comment by marcospassos** [comment]
HI @MidnightDesign, I'm a bit busy these days, but I'll try to take a look at this over the next week.

**Pull request closed without merging**
